name = "todoist-chart"
main = "src/worker.ts"
compatibility_date = "2023-06-25"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 7 * * MON"] # 0 7 * * MON = run At 07:00 on Monday
